# Nixpacks configuration for Railway deployment
# This ensures proper handling of npm workspaces

[phases.setup]
# Ensure we have the correct Node.js version
nixPkgs = ["nodejs_22", "npm-9_x", "openssl"]

[phases.install]
# Install dependencies for the monorepo
# First install root dependencies, then backend
cmds = [
    "npm install --production=false",
    "cd backend && npm install --production=false"
]

[phases.build]
# Build the backend specifically
cmds = [
    "cd backend && npx prisma generate",
    "cd backend && npm run build"
]

[start]
# Start the backend service
cmd = "cd backend && npm start"