services:
  - type: web
    name: article-saver-analytics
    plan: free
    env: docker
    dockerfilePath: ./analytics/Dockerfile
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false