# Quick Fix for NPM Install Failures in GitHub Actions
# This workflow implements the most critical fixes for memory exhaustion and disk space issues

name: Quick Fix - NPM Install

on:
  workflow_dispatch:  # Manual trigger for testing
  pull_request:
    branches: [main]

jobs:
  test-npm-install:
    name: Test NPM Install with Fixes
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
      - uses: actions/checkout@v4
      
      # CRITICAL FIX 1: Free up disk space (adds ~30GB free space)
      - name: Free Disk Space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true
      
      # CRITICAL FIX 2: Add swap space for memory
      - name: Setup 8GB Swap Space
        run: |
          sudo fallocate -l 8G /swapfile
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile
          echo "Swap space added:"
          free -h
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.19.0'
      
      # CRITICAL FIX 3: Configure npm for stability
      - name: Configure NPM
        run: |
          npm install -g npm@10.2.5
          npm config set maxsockets 5
          npm config set fetch-retries 5
          npm config set fetch-retry-mintimeout 20000
          npm config set fetch-retry-maxtimeout 120000
          npm config set prefer-offline true
          npm config set progress false
          npm config set audit false
          npm config set fund false
      
      # CRITICAL FIX 4: Cache everything possible
      - name: Cache NPM Dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            **/node_modules
          key: ${{ runner.os }}-npm-all-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-all-
      
      # CRITICAL FIX 5: Install with maximum memory allocation
      - name: Install Dependencies
        env:
          NODE_OPTIONS: --max-old-space-size=8192
          UV_THREADPOOL_SIZE: 1
          FORCE_COLOR: 0
        run: |
          echo "System resources before install:"
          free -h && df -h
          
          # Try npm ci first (fastest)
          npm ci --no-audit --no-fund || {
            echo "npm ci failed, trying npm install..."
            rm -rf node_modules **/node_modules
            npm install --no-audit --no-fund
          }
          
          echo "System resources after install:"
          free -h && df -h
      
      # Verify installation succeeded
      - name: Verify Installation
        run: |
          echo "Checking backend dependencies..."
          cd backend && npm list --depth=0
          echo "Checking desktop dependencies..."
          cd ../desktop && npm list --depth=0