name: Enterprise CI/CD

on:
  push:
    branches: [main]
    tags:
      - 'v*'
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  NODE_VERSION: '18.19.0'
  NPM_VERSION: '10.2.5'

jobs:
  test-and-lint:
    name: Test and Lint
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      
      - name: Maximize build space
        run: |
          echo "=== Before cleanup ==="
          df -h
          free -m
          
          # Aggressive cleanup for maximum space
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf /opt/hostedtoolcache/CodeQL
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /usr/local/share/boost
          sudo rm -rf /usr/share/swift
          sudo rm -rf /usr/local/.ghcup
          sudo docker system prune -af
          sudo apt-get clean
          sudo apt-get autoremove -y
          sudo apt-get autoclean -y
          
          echo "=== After cleanup ==="
          df -h
          free -m
      
      - name: Setup large swap space
        run: |
          sudo swapoff -a
          sudo fallocate -l 16G /mnt/swapfile
          sudo chmod 600 /mnt/swapfile
          sudo mkswap /mnt/swapfile
          sudo swapon /mnt/swapfile
          echo "=== Swap enabled ==="
          free -m
          sudo swapon --show
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      
      - name: Setup npm with optimizations
        run: |
          npm install -g npm@${{ env.NPM_VERSION }}
          npm config set audit false
          npm config set fund false
          npm config set progress false
          npm config set maxsockets 3
          npm config set fetch-retries 5
          npm config set fetch-retry-maxtimeout 120000
          npm config set fetch-retry-mintimeout 20000
      
      - name: Cache npm dependencies
        uses: actions/cache@v3
        id: npm-cache
        with:
          path: |
            ~/.npm
            node_modules
            backend/node_modules
            desktop/node_modules
          key: ${{ runner.os }}-npm-${{ env.NODE_VERSION }}-${{ hashFiles('**/package-lock.json', '**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-${{ env.NODE_VERSION }}-
      
      - name: System diagnostics before install
        run: |
          echo "=== System resources before npm ci ==="
          free -m
          df -h
          nproc
          ulimit -a
          node -e "console.log('Default heap limit:', require('v8').getHeapStatistics().heap_size_limit / 1024 / 1024, 'MB')"
      
      - name: Install dependencies with retry
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 15
          max_attempts: 3
          retry_on: error
          command: |
            set -e
            export NODE_OPTIONS="--max-old-space-size=6144"
            echo "=== Installing dependencies (attempt ${{ github.run_attempt }}) ==="
            
            # Clear npm cache if not first attempt
            if [ "${{ github.run_attempt }}" -gt "1" ]; then
              npm cache clean --force
            fi
            
            # Show configured heap size
            node -e "console.log('Configured heap limit:', require('v8').getHeapStatistics().heap_size_limit / 1024 / 1024, 'MB')"
            
            # Install with workspace support
            npm ci --workspaces --include-workspace-root --prefer-offline --no-audit --no-fund --no-optional --loglevel=error || {
              echo "npm ci failed, checking for detailed errors..."
              cat /home/runner/.npm/_logs/*.log || true
              exit 1
            }
            
            # Ensure electron types are installed in desktop workspace
            cd desktop && npm list electron || npm install --save-dev electron@28.3.3
            cd ..
            
            echo "=== Dependencies installed successfully ==="
      
      - name: System diagnostics after install
        if: always()
        run: |
          echo "=== System resources after npm ci ==="
          free -m
          df -h
          du -sh node_modules || true
          du -sh backend/node_modules || true
          du -sh desktop/node_modules || true
      
      - name: Generate Prisma client
        working-directory: backend
        env:
          NODE_OPTIONS: --max-old-space-size=4096
        run: npm run db:generate
      
      - name: Lint code with memory optimization
        env:
          NODE_OPTIONS: --max-old-space-size=4096
        run: |
          echo "=== Linting Backend ==="
          cd backend
          npm run lint || echo "::warning::Backend has linting warnings"
          
          echo "=== Linting Desktop ==="
          cd ../desktop
          npm run lint || echo "::warning::Desktop has linting warnings"
      
      - name: Type check with memory optimization
        env:
          NODE_OPTIONS: --max-old-space-size=4096
        run: |
          echo "=== Type checking Backend ==="
          cd backend
          npm run type-check || echo "::warning::Backend has type errors"
          
          echo "=== Type checking Desktop ==="
          cd ../desktop
          npm run type-check || echo "::warning::Desktop has type errors"

  deploy-backend:
    name: Deploy Backend
    needs: test-and-lint
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Railway CLI
        run: npm install -g @railway/cli
      
      - name: Deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          cd backend
          railway up --service backend

  build-desktop:
    name: Build Desktop App
    needs: test-and-lint
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    strategy:
      matrix:
        include:
          - os: macos-latest
            platform: mac
          - os: windows-latest
            platform: win
          - os: ubuntu-latest
            platform: linux
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Maximize build space (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /usr/local/share/boost
          sudo apt-get clean
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      
      - name: Setup npm
        run: |
          npm install -g npm@${{ env.NPM_VERSION }}
          npm config set audit false
          npm config set fund false
          npm config set progress false
          npm config set prefer-offline true
      
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            ~/.cache/electron
            ~/.cache/electron-builder
            node_modules
            backend/node_modules
            desktop/node_modules
          key: ${{ runner.os }}-build-${{ env.NODE_VERSION }}-${{ hashFiles('**/package-lock.json', '**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.NODE_VERSION }}-
      
      - name: Install dependencies with retry
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 15
          max_attempts: 3
          retry_on: error
          command: |
            export NODE_OPTIONS="--max-old-space-size=6144"
            npm ci --workspaces --include-workspace-root --prefer-offline --no-audit --no-fund --no-optional || {
              echo "npm ci failed in desktop build"
              cat /home/runner/.npm/_logs/*.log || true
              exit 1
            }
            
            # Ensure electron is properly installed
            cd desktop && npm list electron || npm install --save-dev electron@28.3.3
            cd ..
      
      - name: Build desktop app
        env:
          NODE_OPTIONS: --max-old-space-size=6144
        run: |
          cd desktop
          npm run build
          npm run dist
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform }}-build
          path: |
            desktop/release/*.exe
            desktop/release/*.dmg
            desktop/release/*.AppImage
            desktop/release/*.deb
          retention-days: 30

  create-release:
    name: Create Release
    needs: build-desktop
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: release-artifacts
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          prerelease: false
          generate_release_notes: true
          files: release-artifacts/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}