name: Desktop App Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., 1.0.0)'
        required: true
        type: string

jobs:
  release:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
        
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          
      - name: Install all dependencies
        run: |
          npm ci
          
      - name: Install desktop-specific dependencies
        run: |
          cd desktop
          npm install --no-save
          
      - name: Build backend TypeScript
        run: |
          cd backend
          npm run build
          
      - name: Build desktop TypeScript
        run: |
          cd desktop
          npm run build:prod
          
      - name: Build Electron app
        run: |
          cd desktop
          npm run dist
        env:
          # Required for auto-updater and publishing
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
          # macOS code signing (optional for now)
          # CSC_LINK: ${{ secrets.MAC_CERTS }}
          # CSC_KEY_PASSWORD: ${{ secrets.MAC_CERTS_PASSWORD }}
          # APPLE_ID: ${{ secrets.APPLE_ID }}
          # APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
          # APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          
          # Windows code signing (optional for now)
          # CSC_LINK: ${{ secrets.WINDOWS_CERTS }}
          # CSC_KEY_PASSWORD: ${{ secrets.WINDOWS_CERTS_PASSWORD }}
          
      - name: Publish Release
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          cd desktop
          npx electron-builder --publish always
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ${{ matrix.os }}-dist
          path: |
            desktop/release/*.exe
            desktop/release/*.dmg
            desktop/release/*.AppImage
            desktop/release/*.deb
            desktop/release/*.snap
            desktop/release/*.rpm
            desktop/release/*.zip