name: Desktop App Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., 1.0.0)'
        required: true
        type: string

permissions:
  contents: write
  
jobs:
  release:
    runs-on: ${{ matrix.os }}
    
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
        
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          
      - name: Install root dependencies
        run: npm ci
          
      - name: Setup desktop environment
        run: |
          cd desktop
          rm -rf node_modules || true
          mkdir -p node_modules
          
      - name: Install Electron in desktop
        run: |
          cd desktop
          npm install electron@28.3.3 --save-dev --force
          
      - name: Run postinstall
        run: |
          cd desktop
          npm run postinstall || true
          
      - name: Build backend TypeScript
        run: |
          cd backend
          npm run build
          
      - name: Build desktop TypeScript
        run: |
          cd desktop
          npm run build:prod || npm run build
          
      - name: Build and publish Electron app
        run: |
          cd desktop
          npm run dist
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Publish to GitHub Release
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          cd desktop
          npx electron-builder --publish always
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ${{ matrix.os }}-dist
          path: |
            desktop/release/*.exe
            desktop/release/*.dmg
            desktop/release/*.AppImage
            desktop/release/*.deb
            desktop/release/*.snap
            desktop/release/*.rpm
            desktop/release/*.zip